# Generated by Django 4.2.11 on 2026-01-03 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Striker', 'St'), ('Defender', 'Df'), ('MidFielder', 'Md'), ('GoalKeeper', 'Gk')], max_length=10)),
                ('rating', models.IntegerField(default=70, help_text='Player skill rating (50-100)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_position', models.CharField(choices=[('Striker', 'St'), ('Defender', 'Df'), ('MidFielder', 'Md'), ('GoalKeeper', 'Gk')], default='Striker', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When player left the team', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fair_play.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fair_play.team')),
            ],
            options={
                'verbose_name_plural': 'Team Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fair_play.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('played_at', models.DateTimeField(blank=True, help_text='When the match is/was scheduled', null=True)),
                ('location', models.CharField(blank=True, help_text='Match venue', max_length=200)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Played', 'Played'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('score_a', models.IntegerField(blank=True, help_text='Team A goals', null=True)),
                ('score_b', models.IntegerField(blank=True, help_text='Team B goals', null=True)),
                ('team_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='fair_play.team')),
                ('team_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='fair_play.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.IntegerField(blank=True, help_text='Minutes played in the match', null=True)),
                ('goals', models.IntegerField(default=0, help_text='Goals scored')),
                ('assists', models.IntegerField(default=0, help_text='Assists made')),
                ('match_rating', models.IntegerField(blank=True, help_text='Match performance rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='fair_play.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='fair_play.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to='fair_play.team')),
            ],
            options={
                'ordering': ['-match__date_created'],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
