# Generated by Django 4.2.11 on 2025-12-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Striker', 'St'), ('Defender', 'Df'), ('MidFielder', 'Md'), ('GoalKeeper', 'Gk')], max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='fair_play.player')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('team_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='fair_play.team')),
                ('team_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='fair_play.team')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
