# Generated by Django 4.2.11 on 2025-12-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fair_play', '0003_team_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, help_text='Match venue', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='played_at',
            field=models.DateTimeField(blank=True, help_text='When the match is/was scheduled', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(blank=True, help_text='Team A goals', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(blank=True, help_text='Team B goals', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Played', 'Played'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now=True, null=True)),
                ('left_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='fair_play.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_play.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_play.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fair_play.team')),
            ],
        ),
    ]
