# Generated by Django 4.2.11 on 2025-12-17 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair_play', '0003_remove_team_players_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=3, help_text='Player skill rating (50-100)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
